-- create database
CREATE DATABASE swp391_fitness_website COLLATE Latin1_General_100_CI_AS_SC_UTF8;

-- 001.sql
-- --> ACCOUNT, PERSONAL_TRAINER, GYMER, CERTIFICATE

-- 002.sql
-- --> BOXCHAT, MESSAGE

-- 003.sql
-- --> REPORT, EVALUATION, ORDER

-- 004.sql
-- --> EXERCISE, NUTRITION, NUTRITION_TRACKING

-- 005.sql
-- --> SCHEDULER, SLOT_EXERCISE, SLOT_NUTRITION, SLOT_EXERCISE_DETAILS, SLOT_NUTRITION_DETAILS