-- Patches to creating tables
-- ACCOUNT, PERSONAL_TRAINER, GYMER, CERTIFICATE

USE swp391_fitness_website;
GO

-- Disable foreign key checks temporarily
EXEC sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';

-- ... (Database creation and foreign key checks)

-- Create table ACCOUNT
IF OBJECT_ID('dbo.ACCOUNT', 'U') IS NOT NULL
    DROP TABLE dbo.ACCOUNT;

CREATE TABLE dbo.ACCOUNT(
    ACCOUNT_ID INT IDENTITY(1,1) PRIMARY KEY,
    FULLNAME NVARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    [PASSWORD] VARCHAR(30) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('F', 'M', 'O')),
	PHONE VARCHAR(20),
    COIN INT DEFAULT(0),
    BIRTHDAY DATE,
    [ADDRESS] NVARCHAR(MAX),
    [ROLE] VARCHAR(5) NOT NULL,
    IS_BAN BIT DEFAULT(0),
	AVATAR_IMAGE VARBINARY(MAX),
    CONSTRAINT UNQ_ACCOUNT_EMAIL UNIQUE (EMAIL)
);

-- Create table PERSONAL_TRAINER
IF OBJECT_ID('dbo.PERSONAL_TRAINER', 'U') IS NOT NULL
    DROP TABLE dbo.PERSONAL_TRAINER;

CREATE TABLE dbo.PERSONAL_TRAINER(
    PT_ID INT IDENTITY(1,1) PRIMARY KEY,
    BANK_NAME VARCHAR(255),
    BANK_NUMBER VARCHAR(30), 
    [DESC] VARCHAR(MAX), 
    IS_ACTIVE BIT DEFAULT(0),
    PRICE INT,
	ACCOUNT_ID INT,
	CONSTRAINT FK_PERSONAL_TRAINER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES dbo.ACCOUNT(ACCOUNT_ID)
);

-- Create table GYMER
IF OBJECT_ID('dbo.GYMER', 'U') IS NOT NULL
    DROP TABLE dbo.GYMER;

CREATE TABLE dbo.GYMER(
    GYMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    [WEIGHT] FLOAT,
    HEIGHT FLOAT,
    GOAL NVARCHAR(MAX),
	ACCOUNT_ID INT,
	CONSTRAINT FK_GYMER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES dbo.ACCOUNT(ACCOUNT_ID)
);

-- Create table CERTIFICATE
IF OBJECT_ID('dbo.CERTIFICATE', 'U') IS NOT NULL
    DROP TABLE dbo.[CERTIFICATE];

CREATE TABLE dbo.[CERTIFICATE](
    CERTIFICATE_ID INT IDENTITY(1,1) PRIMARY KEY,
    TITLE NVARCHAR(255) NOT NULL,
    ORGANIZER NVARCHAR(255) NOT NULL,
    [IMAGE] VARBINARY(MAX) NOT NULL,
    PT_ID INT,
	CONSTRAINT FK_CERTIFICATE_PERSONAL_TRAINER FOREIGN KEY (PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);

-- Enable foreign key checks
EXEC sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL';
