-- Patches to creating tables
-- BOXCHAT, MESSAGE

USE swp391_fitness_website;
GO

-- Create table BOXCHAT
IF OBJECT_ID('dbo.BOXCHAT', 'U') IS NOT NULL
    DROP TABLE dbo.BOXCHAT;

CREATE TABLE dbo.BOXCHAT(
    BOXCHAT_ID INT IDENTITY(1,1) PRIMARY KEY,
    ACCOUNT_1 INT NOT NULL,
    ACCOUNT_2 INT NOT NULL,
    CONSTRAINT FK_BOXCHAT_ACCOUNT_1 FOREIGN KEY(ACCOUNT_1) REFERENCES dbo.ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_BOXCHAT_ACCOUNT_2 FOREIGN KEY(ACCOUNT_2) REFERENCES dbo.ACCOUNT(ACCOUNT_ID)
);

-- Create table MESSAGE
IF OBJECT_ID('dbo.MESSAGE', 'U') IS NOT NULL
    DROP TABLE dbo.MESSAGE;

CREATE TABLE dbo.MESSAGE(
    MESSAGE_ID INT IDENTITY(1,1) PRIMARY KEY,
    SENDER_ID INT NOT NULL,
    CONTENT NVARCHAR(MAX) NOT NULL,
    [TIMESTAMP] DATETIME,
    BOXCHAT_ID INT,
    CONSTRAINT FK_MESSAGE_BOXCHAT FOREIGN KEY (BOXCHAT_ID) REFERENCES dbo.BOXCHAT(BOXCHAT_ID)
);

