-- Patches to creating tables
-- REPORT, EVALUATION, ORDER

USE swp391_fitness_website;
GO

-- Create table REPORT
IF OBJECT_ID('dbo.REPORT', 'U') IS NOT NULL
    DROP TABLE dbo.REPORT;

CREATE TABLE dbo.REPORT(
    REPORT_ID INT IDENTITY(1,1) PRIMARY KEY,
    TITLE NVARCHAR(255),
    [DESC] NVARCHAR(MAX),
    [TIMESTAMP] DATETIME,
    GYMER_ID INT,
    PT_ID INT,
    CONSTRAINT FK_REPORT_GYMER FOREIGN KEY(GYMER_ID) REFERENCES dbo.GYMER(GYMER_ID),
    CONSTRAINT FK_REPORT_PERSONAL_TRAINER FOREIGN KEY(PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);

-- Create table EVALUATION
IF OBJECT_ID('dbo.EVALUATION', 'U') IS NOT NULL
    DROP TABLE dbo.EVALUATION;

CREATE TABLE dbo.EVALUATION(
    EVALUATION_ID INT IDENTITY(1,1) PRIMARY KEY,
    STAR INT NOT NULL,
    CONTENT NVARCHAR(MAX) NOT NULL,
    [TIMESTAMP] DATETIME,
    GYMER_ID INT,
    PT_ID INT,
    CONSTRAINT FK_EVALUATION_GYMER FOREIGN KEY(GYMER_ID) REFERENCES dbo.GYMER(GYMER_ID),
    CONSTRAINT FK_EVALUATION_PERSONAL_TRAINER FOREIGN KEY(PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);

-- Create table ORDER
IF OBJECT_ID('dbo.ORDER', 'U') IS NOT NULL
    DROP TABLE dbo.[ORDER];

CREATE TABLE dbo.[ORDER](
    ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
    TITLE NVARCHAR(255),
    [DESC] NVARCHAR(MAX),
    DATETIME_START DATETIME NOT NULL,
    DATETIME_END DATETIME NOT NULL,
    TOTAL_OF_MONEY INT NOT NULL,
    [STATUS] VARCHAR(20),
    GYMER_ID INT,
    PT_ID INT,
    CONSTRAINT FK_ORDER_GYMER FOREIGN KEY(GYMER_ID) REFERENCES dbo.GYMER(GYMER_ID),
    CONSTRAINT FK_ORDER_PERSONAL_TRAINER FOREIGN KEY(PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);
