-- Patches to creating tables
-- EXERCISE, NUTRITION, NUTRITION_TRACKING

USE swp391_fitness_website;
GO

-- Create table EXERCISE
IF OBJECT_ID('dbo.EXERCISE', 'U') IS NOT NULL
    DROP TABLE dbo.EXERCISE;

CREATE TABLE dbo.EXERCISE(
    EXERCISE_ID INT IDENTITY(1,1) PRIMARY KEY,
    [NAME] NVARCHAR(255),
    MUSCLE_GROUP NVARCHAR(20),
    [DESC] NVARCHAR(MAX),
    [LEVEL] VARCHAR(20),
	GYM_EQUIPMENT VARCHAR(255),
    VIDEO_DESC VARCHAR(MAX),
    IMAGE_DESC VARBINARY(MAX),
	IS_PRIVATE BIT NOT NULL,
    PT_ID INT,
    CONSTRAINT FK_EXERCISE_PERSONAL_TRAINER FOREIGN KEY(PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);

-- Create table NUTRITION
IF OBJECT_ID('dbo.NUTRITION', 'U') IS NOT NULL
    DROP TABLE dbo.NUTRITION;

CREATE TABLE dbo.NUTRITION(
    NUTRITION_ID INT IDENTITY(1,1) PRIMARY KEY,
    [NAME] NVARCHAR(255),
    PROTEIN FLOAT,
    FAT FLOAT,
    CARB FLOAT,
    CALO_IN FLOAT,
	IMAGE_DESC VARBINARY(MAX),
	IS_PRIVATE BIT NOT NULL,
    PT_ID INT,
    CONSTRAINT FK_NUTRITION_PERSONAL_TRAINER FOREIGN KEY(PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);

-- Create table NUTRITION_TRACKING
IF OBJECT_ID('dbo.NUTRITION_TRACKING', 'U') IS NOT NULL
    DROP TABLE dbo.NUTRITION_TRACKING;

CREATE TABLE dbo.NUTRITION_TRACKING(
    NUTRITION_TRACKING_ID INT IDENTITY(1,1) PRIMARY KEY,
    AMOUNT FLOAT,
    [SESSION] VARCHAR(20),
    [DATE] DATE,
    PROTEIN FLOAT,
    FAT FLOAT,
    CARB FLOAT,
    CALO_IN FLOAT,
    GYMER_ID INT,
    NUTRITION_ID INT,
    CONSTRAINT FK_NUTRITION_TRACKING_GYMER FOREIGN KEY(GYMER_ID) REFERENCES dbo.GYMER(GYMER_ID),
    CONSTRAINT FK_NUTRITION_TRACKING_NUTRITION FOREIGN KEY(NUTRITION_ID) REFERENCES dbo.NUTRITION(NUTRITION_ID)
);
