-- Patches to creating tables
-- SCHEDULER, SLOT_EXERCISE, SLOT_NUTRITION. SLOT_EXERCISE_DETAILS, SLOT_NUTRITION_DETAILS

USE swp391_fitness_website;
GO

-- Create table SCHEDULER
IF OBJECT_ID('dbo.SCHEDULER', 'U') IS NOT NULL
    DROP TABLE dbo.SCHEDULER;

CREATE TABLE dbo.SCHEDULER(
    SCHEDULER_ID INT IDENTITY(1,1) PRIMARY KEY,
    GYMER_ID INT,
    PT_ID INT,
    CONSTRAINT FK_SCHEDULER_GYMER FOREIGN KEY(GYMER_ID) REFERENCES dbo.GYMER(GYMER_ID),
    CONSTRAINT FK_SCHEDULER_PERSONAL_TRAINER FOREIGN KEY(PT_ID) REFERENCES dbo.PERSONAL_TRAINER(PT_ID)
);

-- Create table SLOT_EXERCISE
IF OBJECT_ID('dbo.SLOT_EXERCISE', 'U') IS NOT NULL
    DROP TABLE dbo.SLOT_EXERCISE;

CREATE TABLE dbo.SLOT_EXERCISE(
    SLOT_EXERCISE_ID INT IDENTITY(1,1) PRIMARY KEY,
    [DESC] NVARCHAR(MAX),
    ATTENDANT_STATUS VARCHAR(10),
    DATETIME_START DATETIME,
    DATETIME_END DATETIME,
	IS_PENDING BIT,
    SCHEDULER_ID INT,
    CONSTRAINT FK_SLOT_EXERCISE_SCHEDULER FOREIGN KEY(SCHEDULER_ID) REFERENCES dbo.SCHEDULER(SCHEDULER_ID)
);

-- Create table SLOT_NUTRITION
IF OBJECT_ID('dbo.SLOT_NUTRITION', 'U') IS NOT NULL
    DROP TABLE dbo.SLOT_NUTRITION;

CREATE TABLE dbo.SLOT_NUTRITION(
    SLOT_NUTRITIONE_ID INT IDENTITY(1,1) PRIMARY KEY,
    [DESC] NVARCHAR(255),
    DATETIME_START DATETIME,
    DATETIME_END DATETIME,
    SCHEDULER_ID INT,
    CONSTRAINT FK_SLOT_NUTRITION_SCHEDULER FOREIGN KEY(SCHEDULER_ID) REFERENCES dbo.SCHEDULER(SCHEDULER_ID)
);

-- Create table SLOT_EXERCISE_DETAILS
IF OBJECT_ID('dbo.SLOT_EXERCISE_DETAILS', 'U') IS NOT NULL
    DROP TABLE dbo.SLOT_EXERCISE_DETAILS;

CREATE TABLE dbo.SLOT_EXERCISE_DETAILS(
    SLOT_EXERCISE_DETAILS_ID INT IDENTITY(1,1) PRIMARY KEY,
    [SET] INT,
    REP INT,
    SLOT_EXERCISE_ID INT,
    EXERCISE_ID INT,
    CONSTRAINT FK_SLOT_EXERCISE_DETAILS_SLOT_EXERCISE FOREIGN KEY(SLOT_EXERCISE_ID) REFERENCES dbo.SLOT_EXERCISE(SLOT_EXERCISE_ID),
    CONSTRAINT FK_SLOT_EXERCISE_DETAILS_EXERCISE FOREIGN KEY(EXERCISE_ID) REFERENCES dbo.EXERCISE(EXERCISE_ID)
);

-- Create table SLOT_NUTRITION_DETAILS
IF OBJECT_ID('dbo.SLOT_NUTRITION_DETAILS', 'U') IS NOT NULL
    DROP TABLE dbo.SLOT_NUTRITION_DETAILS;

CREATE TABLE dbo.SLOT_NUTRITION_DETAILS(
    SLOT_NUTRITION_DETAIL_ID INT IDENTITY(1,1) PRIMARY KEY,
    AMOUNT FLOAT,
    SLOT_NUTRITIONE_ID INT,
    NUTRITION_ID INT,
    CONSTRAINT FK_SLOT_NUTRITION_DETAILS_SLOT_NUTRITION FOREIGN KEY(SLOT_NUTRITIONE_ID) REFERENCES dbo.SLOT_NUTRITION(SLOT_NUTRITIONE_ID),
    CONSTRAINT FK_SLOT_NUTRITION_DETAILS_NUTRITION FOREIGN KEY(NUTRITION_ID) REFERENCES dbo.NUTRITION(NUTRITION_ID)
);
