USE swp391_fitness_website;
GO
-- Disable foreign key constraints
EXEC sp_msforeachtable @command1="ALTER TABLE ? NOCHECK CONSTRAINT all"

-- Delete data
DELETE FROM ACCOUNT
DELETE FROM PERSONAL_TRAINER
DELETE FROM GYMER  
DELETE FROM [CERTIFICATE]
DELETE FROM BOXCHAT
DELETE FROM [MESSAGE]
DELETE FROM REPORT
DELETE FROM EVALUATION
DELETE FROM [ORDER]
DELETE FROM EXERCISE
DELETE FROM NUTRITION
DELETE FROM NUTRITION_TRACKING
DELETE FROM SCHEDULER
DELETE FROM SLOT_EXERCISE
DELETE FROM SLOT_NUTRITION
DELETE FROM SLOT_EXERCISE_DETAILS
DELETE FROM SLOT_NUTRITION_DETAILS

-- Re-enable foreign key constraints 
EXEC sp_msforeachtable @command1="ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"