USE swp391_fitness_website;
GO

SELECT * FROM ACCOUNT;
SELECT * FROM PERSONAL_TRAINER;
SELECT * FROM GYMER;
SELECT * FROM [CERTIFICATE];
SELECT * FROM BOXCHAT;
SELECT * FROM [MESSAGE];
SELECT * FROM REPORT;
SELECT * FROM EVALUATION;
SELECT * FROM [ORDER];
SELECT * FROM EXERCISE;
SELECT * FROM NUTRITION;
SELECT * FROM NUTRITION_TRACKING;
SELECT * FROM SCHEDULER;
SELECT * FROM SLOT_EXERCISE;
SELECT * FROM SLOT_NUTRITION;
SELECT * FROM SLOT_EXERCISE_DETAILS;
SELECT * FROM SLOT_NUTRITION_DETAILS;